#!/usr/bin/env python3
"""Regenerate profile.js from the resume kept in ~/small_apps/ai_self.

    python3 about/build.py [path/to/ai_self]

ai_self is a private notes repo and this site is public, so only the resume is
read, and only the fields listed in build() are written out. Phone and email
are deliberately left out.
"""
import json
import os
import re
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_AI_SELF = Path.home() / 'small_apps' / 'ai_self'
RESUME = Path('life_admin') / 'resume' / 'resume.txt'

SECTIONS = ('SUMMARY', 'EXPERIENCE', 'EDUCATION', 'SKILLS', 'LANGUAGES')
# "Title (Jan 2024 – Present)"
DATED = re.compile(r'^(?P<title>.+?)\s*\((?P<dates>[^()]*\d{4}[^()]*)\)$')


def split_sections(lines):
    head, sections, current = [], {}, None
    for line in lines:
        if line.strip() in SECTIONS:
            current = sections.setdefault(line.strip(), [])
        elif current is None:
            head.append(line)
        else:
            current.append(line)
    return head, sections


def parse_groups(lines):
    """Unindented lines start a group; indented lines are dated entries with
    optional '* ' bullets underneath."""
    groups = []
    for line in lines:
        text = line.strip()
        if not text:
            continue
        if not line.startswith(' '):
            groups.append({'name': text, 'entries': []})
        elif text.startswith('*'):
            groups[-1]['entries'][-1]['bullets'].append(text.lstrip('* ').strip())
        else:
            m = DATED.match(text)
            groups[-1]['entries'].append({
                'title': m.group('title') if m else text,
                'dates': m.group('dates').replace(' - ', ' – ') if m else '',
                'bullets': [],
            })
    return groups


def build(resume_text):
    head, sections = split_sections(resume_text.splitlines())
    head = [h.strip() for h in head if h.strip()]
    linkedin = re.search(r'https?://\S*linkedin\.com/\S+', resume_text)

    profile = {
        'name': head[0],
        'headline': head[1],
        'location': head[2].split('|')[0].strip(),
        'linkedin': linkedin.group(0) if linkedin else '',
        'summary': ' '.join(l.strip() for l in sections.get('SUMMARY', []) if l.strip()),
        'experience': parse_groups(sections.get('EXPERIENCE', [])),
        'education': parse_groups(sections.get('EDUCATION', [])),
        'skills': [s.strip() for s in ' '.join(sections.get('SKILLS', [])).split(',') if s.strip()],
        'languages': [s.strip() for s in ' '.join(sections.get('LANGUAGES', [])).split(',') if s.strip()],
        'updated': date.today().isoformat(),
    }
    if not profile['experience'] or not profile['summary']:
        sys.exit('Resume did not parse: no summary or experience found. Has its layout changed?')
    return profile


def main():
    root = Path(sys.argv[1] if len(sys.argv) > 1 else os.environ.get('AI_SELF', DEFAULT_AI_SELF))
    source = root.expanduser() / RESUME
    if not source.exists():
        sys.exit(f'Resume not found at {source}')
    profile = build(source.read_text(encoding='utf-8'))
    out = HERE / 'profile.js'
    out.write_text(
        '// Generated by build.py from ai_self/life_admin/resume/resume.txt. Do not edit by hand.\n'
        f'window.PROFILE = {json.dumps(profile, indent=2, ensure_ascii=False)};\n',
        encoding='utf-8')
    roles = sum(len(g['entries']) for g in profile['experience'])
    print(f'Wrote {out} ({roles} roles, {len(profile["education"])} schools)')


if __name__ == '__main__':
    main()
