// Generated by build.py from ai_self/life_admin/resume/resume.txt. Do not edit by hand.
window.PROFILE = {
  "name": "Winston Andersen",
  "headline": "Lead Software Engineer",
  "location": "Singapore",
  "linkedin": "https://linkedin.com/in/winston-andersen",
  "summary": "Lead Software Engineer with over 9 years of experience architecting, scaling, and delivering high-impact financial technology solutions. A proven leader in guiding teams and systems through periods of hyper-growth, helping scale a startup from 15 to over 1000 employees.",
  "experience": [
    {
      "name": "Fazz Financial Group (formerly Xfers), Singapore",
      "entries": [
        {
          "title": "Lead Software Engineer – StraitsX Treasury",
          "dates": "Jan 2024 – Present",
          "bullets": [
            "Lead team of 3-5 engineers developing treasury infrastructure for cryptocurrency platform.",
            "Built BigQuery-based transaction audit system and MAS compliance reporting tools.",
            "Developed cross-system reconciliation platform tracking financial integrity across banking and crypto systems.",
            "Developed stablecoin market making system"
          ]
        },
        {
          "title": "Lead Software Engineer – Fazz Business",
          "dates": "June 2022 – Dec 2023",
          "bullets": [
            "Led backend team of 3-10 engineers building business banking dashboard for cross-border money transfers between Singapore and Indonesia.",
            "Delivered scalable payment infrastructure supporting business-to-business transactions."
          ]
        },
        {
          "title": "Senior Software Engineer – Fazz Agent",
          "dates": "May 2020 – May 2022",
          "bullets": [
            "Spearheaded team of 8 engineers implementing CI/CD pipeline and SRE protocols, reducing deployment failures by 40% and achieving 99.98% uptime.",
            "Directed backend development for high-traffic financial mobile app processing $200M monthly GMV.",
            "Decreased critical incident MTTR by 35% through enhanced monitoring and response protocols."
          ]
        },
        {
          "title": "Senior Software Engineer - Xfers",
          "dates": "June 2018 – April 2020",
          "bullets": [
            "Led 3-engineer team building new backend system, improving API response times by 60%.",
            "Orchestrated Indonesian payment gateway overhaul with 4-person team, supporting 10x transaction volume growth.",
            "Implemented Agile practices reducing bug backlog by 50% and increasing team velocity by 25%."
          ]
        },
        {
          "title": "Software Engineer - Xfers",
          "dates": "April 2017 – June 2018",
          "bullets": [
            "Developed and optimized core payment gateway features, contributing to 20% increase in transactional throughput.",
            "Rapidly promoted through demonstrated technical execution in fast-paced fintech environment."
          ]
        }
      ]
    },
    {
      "name": "Works Applications Co., Ltd., Singapore",
      "entries": [
        {
          "title": "Software Engineer",
          "dates": "Dec 2016 – March 2017",
          "bullets": [
            "Inventory Management Frontend in Jquery."
          ]
        }
      ]
    },
    {
      "name": "PT Bank Central Asia Tbk, Jakarta",
      "entries": [
        {
          "title": "Intern, GSIT Team",
          "dates": "Sept 2016 – Nov 2016",
          "bullets": [
            "Intern at team developing and maintaining BCA.co.id."
          ]
        }
      ]
    },
    {
      "name": "PT. INDAH KIAT PULP, Tangerang",
      "entries": [
        {
          "title": "Marketing Internship",
          "dates": "June 2012 – July 2012",
          "bullets": [
            "Internship in marketing department working in the product sample testing and delivery."
          ]
        }
      ]
    },
    {
      "name": "CV. AKS Jakarta, Greater Jakarta Area",
      "entries": [
        {
          "title": "Marketing Trainee",
          "dates": "May 2010 – July 2010",
          "bullets": [
            "Marketing trainee for Indonesian machine and tools importer that imports products from China."
          ]
        }
      ]
    }
  ],
  "education": [
    {
      "name": "Waseda University, Fukuoka",
      "entries": [
        {
          "title": "Master of Engineering - MEng in Information Architecture (Natural Language Processing)",
          "dates": "Jan 2020 – Jan 2022",
          "bullets": []
        }
      ]
    },
    {
      "name": "The Hong Kong University of Science and Technology",
      "entries": [
        {
          "title": "Bachelor’s Degree in Computer Engineering",
          "dates": "Jan 2012 – Jan 2016",
          "bullets": []
        }
      ]
    }
  ],
  "skills": [
    "Ruby",
    "SQL",
    "Javascript",
    "Golang",
    "DevOps"
  ],
  "languages": [
    "Indonesian (Native)",
    "English (Fluent)",
    "Chinese (Fluent)"
  ],
  "updated": "2026-09-30"
};
